---
exclude: ['README.markdown']
permalink: ':title'
pygments: true
safe: false
title: 'TRUSTEDSearch Developers'
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]